name: Publish package to GitHub Packages
on:
  pull_request:
    branches:
      - 'master'
jobs:
  publish:
    name: Publish package to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Publish package
        run: |
          chmod +x gradlew
          ./gradlew publish
        env:
          RABBIT_HOST: ${{ secrets.RABBIT_HOST }}
          RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          RABBIT_URI: ${{ secrets.RABBIT_URI }}
          RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
          KAFKA_BOOTSTRAP_SERVERS: ${{ secrets.KAFKA_BOOTSTRAP_SERVERS }}
          KAFKA_KEY: ${{ secrets.KAFKA_KEY }}
          KAFKA_SECRET: ${{ secrets.KAFKA_SECRET }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
